version: '3.7'

services:
    php-httpd:
        build: ./
        env_file:
            - php.env
        ports:
            - 80:80
        volumes:
            - "./:/var/www/html"
        links:
            - db
        depends_on:
            - db
        networks:
            - default
    db:
        image: mariadb:latest
        container_name: db
        restart: always
        ports: 
            - "3306:3306"
        env_file:
            - mariadb.env 
        volumes:
            - ./database/:/docker-entrypoint-initdb.d
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        env_file:
            - phpmyadmin.env